const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Behaviors.bound,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.TiledBg,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Flash.Acts.Flash,
		C3.ScriptsInEvents.Folhafase1_Event17_Act3,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.System.Cnds.IsPreview,
		C3.ScriptsInEvents.Folhafase2_Event20_Act2,
		C3.ScriptsInEvents.Folhafase2_Event26_Act2,
		C3.Plugins.System.Cnds.OnResume,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.AddRemoveAnimation,
		C3.ScriptsInEvents.Folhafase2_Event34_Act3
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{Grama: 0},
	{Chaoo: 0},
	{Teclado: 0},
	{Play: 0},
	{Mouse: 0},
	{Arbusto1: 0},
	{Arbusto2: 0},
	{ChaoFlutuante: 0},
	{Áudio: 0},
	{Coin: 0},
	{PararAudio: 0},
	{Abismo: 0},
	{Limbo: 0},
	{Terra: 0},
	{Rampa: 0},
	{CHAOPEDRA: 0},
	{Start: 0},
	{Âncora: 0},
	{pontos: 0},
	{PedraFlutuante: 0},
	{Barreira: 0},
	{RestritoAoLayout: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{Piscar: 0},
	{Cian: 0},
	{Coracao: 0},
	{Coin2: 0},
	{Projétil: 0},
	{DestruirForaDoLayout: 0},
	{Magia: 0},
	{PlanoDeFundoTelaInicial: 0},
	{vidas: 0},
	{açao: 0},
	{Skeleton: 0},
	{textovidas: 0},
	{portal: 0},
	{Jade: 0},
	{Fundofase2: 0},
	{ossosterreno: 0},
	{Lava: 0},
	{OssosVoadores: 0},
	{Sprite3: 0},
	{vidass: 0},
	{movimento: 0},
	{Skeleton2: 0},
	{PortaoPedra: 0},
	{Cenario: 0},
	{Plataforma2: 0},
	{ParedePedra: 0},
	{Pedralava1: 0},
	{PedraLava2: 0},
	{PedraLava3: 0},
	{Cenario3: 0},
	{Porta: 0},
	{NextButton: 0},
	{PlanoFase1: 0},
	{Historia1: 0},
	{Historia2: 0},
	{Historia3: 0},
	{Next: 0},
	{Next2: 0},
	{GameOver1: 0},
	{GameOver2: 0},
	{Yes: 0},
	{No: 0},
	{Yes2: 0},
	{No2: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Vidas: 0},
	{Camus: 0},
	{vidas2: 0},
	{AtackBoss: 0},
	{vidaas: 0}
];

self.InstanceType = {
	Grama: class extends self.ISpriteInstance {},
	Chaoo: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Play: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Arbusto1: class extends self.ISpriteInstance {},
	Arbusto2: class extends self.ISpriteInstance {},
	ChaoFlutuante: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Coin: class extends self.ISpriteInstance {},
	PararAudio: class extends self.ISpriteInstance {},
	Abismo: class extends self.ISpriteFontInstance {},
	Limbo: class extends self.ISpriteInstance {},
	Terra: class extends self.ISpriteInstance {},
	Rampa: class extends self.ISpriteInstance {},
	CHAOPEDRA: class extends self.ISpriteInstance {},
	Start: class extends self.ISpriteInstance {},
	pontos: class extends self.ITextInstance {},
	PedraFlutuante: class extends self.ISpriteInstance {},
	Barreira: class extends self.ISpriteInstance {},
	Cian: class extends self.ISpriteInstance {},
	Coracao: class extends self.ISpriteInstance {},
	Coin2: class extends self.ISpriteInstance {},
	Magia: class extends self.ISpriteInstance {},
	PlanoDeFundoTelaInicial: class extends self.ITiledBackgroundInstance {},
	Skeleton: class extends self.ISpriteInstance {},
	textovidas: class extends self.ITextInstance {},
	portal: class extends self.ISpriteInstance {},
	Jade: class extends self.ISpriteInstance {},
	Fundofase2: class extends self.ITiledBackgroundInstance {},
	ossosterreno: class extends self.ISpriteInstance {},
	Lava: class extends self.ISpriteInstance {},
	OssosVoadores: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Skeleton2: class extends self.ISpriteInstance {},
	Plataforma: class extends self.ISpriteInstance {},
	PortaoPedra: class extends self.ISpriteInstance {},
	Cenario: class extends self.ISpriteInstance {},
	Plataforma2: class extends self.ISpriteInstance {},
	ParedePedra: class extends self.ISpriteInstance {},
	Pedralava1: class extends self.ISpriteInstance {},
	PedraLava2: class extends self.ISpriteInstance {},
	PedraLava3: class extends self.ISpriteInstance {},
	Cenario3: class extends self.ISpriteInstance {},
	Porta: class extends self.ISpriteInstance {},
	NextButton: class extends self.ISpriteFontInstance {},
	PlanoFase1: class extends self.ITiledBackgroundInstance {},
	Historia1: class extends self.ITiledBackgroundInstance {},
	Historia2: class extends self.ITiledBackgroundInstance {},
	Historia3: class extends self.ITiledBackgroundInstance {},
	Next: class extends self.ISpriteFontInstance {},
	Next2: class extends self.ISpriteFontInstance {},
	GameOver1: class extends self.ITiledBackgroundInstance {},
	GameOver2: class extends self.ITiledBackgroundInstance {},
	Yes: class extends self.ISpriteFontInstance {},
	No: class extends self.ISpriteFontInstance {},
	Yes2: class extends self.ISpriteFontInstance {},
	No2: class extends self.ISpriteFontInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Camus: class extends self.ISpriteInstance {},
	vidas2: class extends self.ITextInstance {},
	AtackBoss: class extends self.ISpriteInstance {}
}